/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mascotapp.desktop;

import org.junit.jupiter.api.Test;

import com.mascotapp.core.Library;

import static org.junit.jupiter.api.Assertions.*;

class MascotAppViewTest {
    @Test void isWorkingDependencyProjectMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "isWorkingDependencyProject should return 'true'");
    }
}
