/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mascotapp.desktop;

import org.junit.jupiter.api.Test;

import com.mascotapp.core.entities.Pet;

import static org.junit.jupiter.api.Assertions.*;

class MascotAppViewTest {
    @Test void isWorkingDependencyProjectMethodReturnsTrue() {
    	Pet pet = new Pet("Max", "Perro", null);
    	assertEquals(pet.getAnimalType(), "Perro");
    }
}
