/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mascotapp.desktop;

import org.junit.jupiter.api.Test;

import com.mascotapp.core.entities.Post;

import static org.junit.jupiter.api.Assertions.*;

class MascotAppViewTest {
    @Test void isWorkingDependencyProjectMethodReturnsTrue() {
    	Post post = new Post("Max", "www.facebook.com");
    	assertEquals(post.getContent(), "Max");
    }
}
